disable kunlunxin ci (#960)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,7 +30,7 @@ env:
   CLUSTER_ASCEND_910B: ASCEND-910B
   CLUSTER_TOPSRIDER: TOPSRIDER
   CLUSTER_SUPA: SUPA
-  CLUSTER_KLX: KUNLUNXIN
+  # CLUSTER_KLX: KUNLUNXIN
   BUILD_TEST1: build_test
   BUILD_TEST2: build_test_dy
   BUILD_TEST3: build_mmcv_ext
@@ -97,8 +97,8 @@ jobs:
           && rsync -a --delete ${GITHUB_WORKSPACE}/source/ ${CLUSTER_1424}:${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/source/ || echo "failure to connect to sh1424"
           ssh ${CLUSTER_ASCEND_910B} "mkdir -p ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/source" \
           && rsync -a --delete ${GITHUB_WORKSPACE}/source/ ${CLUSTER_ASCEND_910B}:${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/source/ || echo "failure to connect to ascend 910b"
-          ssh ${CLUSTER_KLX} "mkdir -p ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/source" \
-          && rsync -a --delete ${GITHUB_WORKSPACE}/source/ ${CLUSTER_KLX}:${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/source/ || echo "failure to connect to kunlunxin"
+          # ssh ${CLUSTER_KLX} "mkdir -p ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/source" \
+          # && rsync -a --delete ${GITHUB_WORKSPACE}/source/ ${CLUSTER_KLX}:${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/source/ || echo "failure to connect to kunlunxin"
 
   Runs-On-Nv:
     name: runs on nv
@@ -432,44 +432,43 @@ jobs:
           echo "test and clean, you can refer to the CAMB"
           """
 
+  # Build-Kunlunxin:
+  #   name: Build-Kunlunxin
+  #   runs-on: tps-klx-ci
+  #   needs: Rsync
+  #   if: ${{ contains( needs.Rsync.outputs.output, 'KUNLUNXIN' ) }}
+  #   steps:
+  #     - name: Build
+  #       run: |
+  #         set -e
+  #         export USE_COVERAGE=ON
+  #         cd ${DEEPLINK_PATH}/ && ls -al && find ${DEEPLINK_PATH}/ -maxdepth 1 -mmin +300 -type d |xargs rm -rf
+  #         cd ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER} && rm -rf ${BUILD_TEST1} && cp -R source ${BUILD_TEST1} && cd ${BUILD_TEST1}
+  #         source /mnt/cache/share/deeplinkci/env.sh
+  #         cd impl && bash scripts/build_impl.sh kunlunxin
 
-  Build-Kunlunxin:
-    name: Build-Kunlunxin
-    runs-on: tps-klx-ci
-    needs: Rsync
-    if: ${{ contains( needs.Rsync.outputs.output, 'KUNLUNXIN' ) }}
-    steps:
-      - name: Build
-        run: |
-          set -e
-          export USE_COVERAGE=ON
-          cd ${DEEPLINK_PATH}/ && ls -al && find ${DEEPLINK_PATH}/ -maxdepth 1 -mmin +300 -type d |xargs rm -rf
-          cd ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER} && rm -rf ${BUILD_TEST1} && cp -R source ${BUILD_TEST1} && cd ${BUILD_TEST1}
-          source /mnt/cache/share/deeplinkci/env.sh
-          cd impl && bash scripts/build_impl.sh kunlunxin
-
-  Op-Test-Kunlunxin:
-    name: Op-Test-Kunlunxin
-    runs-on: tps-klx-ci
-    needs: Build-Kunlunxin
-    if: ${{ contains( needs.Rsync.outputs.output, 'KUNLUNXIN' ) }}
-    steps:
-      - name: test
-        run: |
-          set -e
-          cd ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}
-          echo "data is /mnt/cache/share/deeplinkci/data/"
-          cd ${BUILD_TEST1}
-          cd diopi_test/python && mkdir -p cache/diopi
-          ln -sf /mnt/cache/share/deeplinkci/data/inputs ./cache/diopi && ln -sf /mnt/cache/share/deeplinkci/data/outputs ./cache/diopi && ln -sf /mnt/cache/share/deeplinkci/data/diopi_case_items.cfg ./cache/diopi
-          python main.py --mode gen_case --impl_folder ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/${BUILD_TEST1}/impl/kunlunxin/
-          python main.py --mode run_test
-          if [ "${ALL_COVERAGE}" = "ON" ]; then
-             bash /mnt/cache/share/platform/dep/sonar/coverage_DIOPI.sh ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/${BUILD_TEST1} || echo "get coverage fail"
-          fi
-      - name: increment coverage check
-        if: ${{ contains( github.event_name, 'pull_request' ) && contains( github.base_ref, 'main' ) }}
-        run: |
-          set -e
-          cd ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/${BUILD_TEST1}
-          bash scripts/increment_coverage.sh ${REQUIRE_COVERAGE}
+  # Op-Test-Kunlunxin:
+  #   name: Op-Test-Kunlunxin
+  #   runs-on: tps-klx-ci
+  #   needs: Build-Kunlunxin
+  #   if: ${{ contains( needs.Rsync.outputs.output, 'KUNLUNXIN' ) }}
+  #   steps:
+  #     - name: test
+  #       run: |
+  #         set -e
+  #         cd ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}
+  #         echo "data is /mnt/cache/share/deeplinkci/data/"
+  #         cd ${BUILD_TEST1}
+  #         cd diopi_test/python && mkdir -p cache/diopi
+  #         ln -sf /mnt/cache/share/deeplinkci/data/inputs ./cache/diopi && ln -sf /mnt/cache/share/deeplinkci/data/outputs ./cache/diopi && ln -sf /mnt/cache/share/deeplinkci/data/diopi_case_items.cfg ./cache/diopi
+  #         python main.py --mode gen_case --impl_folder ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/${BUILD_TEST1}/impl/kunlunxin/
+  #         python main.py --mode run_test
+  #         if [ "${ALL_COVERAGE}" = "ON" ]; then
+  #            bash /mnt/cache/share/platform/dep/sonar/coverage_DIOPI.sh ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/${BUILD_TEST1} || echo "get coverage fail"
+  #         fi
+  #     - name: increment coverage check
+  #       if: ${{ contains( github.event_name, 'pull_request' ) && contains( github.base_ref, 'main' ) }}
+  #       run: |
+  #         set -e
+  #         cd ${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}/${BUILD_TEST1}
+  #         bash scripts/increment_coverage.sh ${REQUIRE_COVERAGE}
